"""empty message

Revision ID: 29908638c0df
Revises: None
Create Date: 2015-09-30 13:15:15.705305

"""

# revision identifiers, used by Alembic.
revision = '29908638c0df'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('htoken', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appusers',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('app_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('check',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('dynotype', sa.String(length=64), nullable=True),
    sa.Column('params', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check')
    op.drop_table('appusers')
    op.drop_table('user')
    op.drop_table('app')
    ### end Alembic commands ###
